"""add tables for upvote and down votes

Revision ID: 0d7c17dde503
Revises: 3040f47cc5b6
Create Date: 2021-06-16 01:06:14.016862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d7c17dde503'
down_revision = '3040f47cc5b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('descrption', sa.Text(), nullable=True))
    op.drop_column('pitches', 'post_pitch')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('post_pitch', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('pitches', 'descrption')
    # ### end Alembic commands ###
