"""change description

Revision ID: 3760e816e6ba
Revises: 4654f7488d1c
Create Date: 2021-06-17 16:12:29.844028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3760e816e6ba'
down_revision = '4654f7488d1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'pitch_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('pitch_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
