"""added comments model

Revision ID: 74cce18ddfd4
Revises: dfdfb8f675e0
Create Date: 2021-06-14 01:55:44.539567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74cce18ddfd4'
down_revision = 'dfdfb8f675e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pitch_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pitch_id'], ['pitches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('pitches', sa.Column('time', sa.DateTime(), nullable=True))
    op.add_column('pitches', sa.Column('categories', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_pitches_categories'), 'pitches', ['categories'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pitches_categories'), table_name='pitches')
    op.drop_column('pitches', 'categories')
    op.drop_column('pitches', 'time')
    op.drop_table('comments')
    # ### end Alembic commands ###
