"""updadte bio

Revision ID: 9b3bc308cd93
Revises: 74cce18ddfd4
Create Date: 2021-06-14 18:46:32.558966

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9b3bc308cd93'
down_revision = '74cce18ddfd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('date_posted', sa.DateTime(), nullable=True))
    op.add_column('pitches', sa.Column('category', sa.String(length=255), nullable=False))
    op.drop_index('ix_pitches_categories', table_name='pitches')
    op.create_index(op.f('ix_pitches_category'), 'pitches', ['category'], unique=False)
    op.drop_column('pitches', 'categories')
    op.drop_column('pitches', 'time')
    op.add_column('users', sa.Column('bio', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bio')
    op.add_column('pitches', sa.Column('time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('pitches', sa.Column('categories', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_pitches_category'), table_name='pitches')
    op.create_index('ix_pitches_categories', 'pitches', ['categories'], unique=False)
    op.drop_column('pitches', 'category')
    op.drop_column('pitches', 'date_posted')
    # ### end Alembic commands ###
