"""update table

Revision ID: 9c858f63072b
Revises: 7c9e02568af4
Create Date: 2021-06-15 08:31:50.829789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c858f63072b'
down_revision = '7c9e02568af4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('post_pitch', sa.Text(), nullable=False))
    op.drop_column('pitches', 'post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('post', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('pitches', 'post_pitch')
    # ### end Alembic commands ###
